version: '3'
services:
  alpine_tomcat:
    build: .
    container_name: alpine_tomcat
    restart: always
    ports:
      - 8082:8080
    tty: true
    volumes:
      - $HOME/Dev/Docker/vscode-remote/vscode-remote-tomcat:/workspaces
    networks:
      - remote-container_common-network
#    depends_on:
#      - postgresql
networks:
  remote-container_common-network:
    external: true